### ISSUE TITLE
Support proposed widget v2 spec

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-dimension#182]
Reference document: https://docs.google.com/document/d/1uPF7XWY_dXTKVKV7jZQ2KmsI19wn9-kFRgQ1tFQP7wQ/edit

This is an epic to track the various components to have this spec implemented in Dimension.

* [x] Update the Jitsi widget (https://github.com/turt2live/matrix-dimension/issues/176)
* [x] TradingView Widget (https://github.com/turt2live/matrix-dimension/issues/132)
  * Followup: https://github.com/turt2live/matrix-dimension/issues/261
* [x] Spotify Widget (https://github.com/turt2live/matrix-dimension/issues/133)
* [x] Update the Youtube widget (https://github.com/turt2live/matrix-dimension/issues/177)
* [x] Update the Google Docs widget (https://github.com/turt2live/matrix-dimension/issues/178)
* [x] Update the Google Calendar widget (https://github.com/turt2live/matrix-dimension/issues/179)
* [x] Update the Etherpad widget (https://github.com/turt2live/matrix-dimension/issues/180)
* [x] Grafana Widget (https://github.com/turt2live/matrix-dimension/issues/86)
* [x] Update Custom widgets (https://github.com/turt2live/matrix-dimension/issues/181)
* [x] Specify `waitForIframeLoad` (https://github.com/turt2live/matrix-dimension/issues/143)
* [x] Specify `creatorUserId` (https://github.com/turt2live/matrix-dimension/issues/167)
* [x] Widget PostMessage API (https://github.com/turt2live/matrix-dimension/issues/152)
* [x] Widget screenshots as a POC for the PostMessage API (https://github.com/turt2live/matrix-dimension/issues/155)
* [x] Sticker Packs - currently without spec (https://github.com/turt2live/matrix-dimension/issues/156)
* [x] Use new widget types (https://github.com/turt2live/matrix-dimension/issues/182)
